name: MCzofrenic-Islands
version: '${project.version}'
main: mi.s4lpicon.mczofrenicislands.MCzofrenic_Islands
api-version: '1.21'
authors:
  - S4LPICON
  - Phancha
description: Player Island Manager

commands:
  island:
    description: MCzofrenic-Islands Main Command.
    usage: /<command> <Args>
  spawn:
    description: Teleport to the server spawn.
    usage: /<command> <Args>
  devinfo:
    description: De-bug Information

permissions:
  mczofrenicisland.admin:
    description: "Permite al jugador administrar el plugin"
    default: op
  mczofrenicisland.vip:
    description: "Permite al jugador acceder a benefices vip"
  mczofrenicisland.pro:
    description: "Permite al jugador acceder a benefices pro"
  mczofrenicisland.elite:
    description: "Permite al jugador acceder a benefices elite"