name: MCzofrenic-Islands
version: '${project.version}'
main: mi.s4lpicon.mczofrenicislands.MCzofrenic_Islands
api-version: '1.21'
authors:
  - S4LPICON
  - Phancha
description: Player Island Manager

commands:
  island:
    description: MCzofrenic-Islands Main Command.
    usage: /<command> <Args>